apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: print-env
spec:
  version: {{ .TagName }}
  platforms:
  - bin: kubectl-print-env.exe
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_windows_arm64.zip" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: arm64
  - bin: kubectl-print-env.exe
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_windows_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: amd64
  - bin: kubectl-print-env
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: kubectl-print-env
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: kubectl-print-env
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: kubectl-print-env
    {{addURIAndSha "https://github.com/pedrobarco/kubectl-print-env/releases/download/{{ .TagName }}/kubectl-print-env_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  shortDescription: Build config files from k8s environments.
  homepage: https://github.com/pedrobarco/kubectl-print-env
  description: |
    Prints a config file by parsing environment information about the specified
    resources. You can select the output format using the --output flag.

